#!/bin/bash -eu

source ./cmip5_functions

RUNNING=$(qstat | grep -P "r\d{1,2}i\dp\d" | cut -d " " -f2)

now=$(date +%s)
conv_date=`date -d "$(ls -l prepare.txt | cut -d " " -f6-7)" +%s`
if [ $[$now-$conv_date] -gt 3600 ]
then
  :
  python cmip_prepare_bot.py /stornext/online14/ocean/cmip5_send/output/INPE/BESM-OA2-3/
fi

grep decadal prepare.txt| while read EXP;
do
  LOGYEAR=$(echo $EXP|cut -d " " -f1 | cut -d "l" -f2)
  LOGMEMBER=$(echo $EXP| cut -d " " -f2)
  LOGREALM=$(echo $EXP|cut -d " " -f3 | cut -c1)
  EXPNAME_BASE=${LOGYEAR:2:4}${LOGMEMBER}${LOGREALM}
  if [ $LOGREALM != 'l' ]
  then
    NUM=$(echo $EXP | cut -d " " -f4)
    DEN=$(echo $EXP | cut -d " " -f5)
    DONE=$(awk -vnum="$NUM" -vden="$DEN" 'BEGIN{print (num >= den)?1:0 }')
    if [ $DONE -eq 1 ]
    then
      echo $EXPNAME_BASE OK
    else
        #MISSING=$(grep $EXPNAME_BASE conversion_nodes_full.txt|cut -d " " -f3)
        grep $EXPNAME_BASE prepare.txt|cut -d " " -f3 | while read MISSING;
        do
          log=$(echo workdir_nodes/copy_out/${EXPNAME_BASE}${MISSING:2:4}.*.out.txt | tail -1)
          EXPNAME=$(echo $log|cut -d '.' -f1 | cut -d "/" -f3)
          echo $EXPNAME TODO
       done
    fi
  fi
done
