#!/bin/bash -eu

source ./cmip5_functions

RUNNING=$(qstat @aux20 | grep -P "_r\d{1,2}i\dp\d_" | cut -d " " -f2)

now=$(date +%s)
conv_date=`date -d "$(ls -l conversion.txt | cut -d " " -f6-7)" +%s`
if [ $[$now-$conv_date] -gt 900 ]
then
  python cmip_restart_bot.py
fi

cat conversion.txt | while read EXP; 
do
  LOGYEAR=$(echo $EXP|cut -d " " -f1 | cut -d "l" -f2)
  LOGMEMBER=$(echo $EXP| cut -d " " -f2)
  LOGREALM=$(echo $EXP|cut -d " " -f3 | cut -c1)
  if [ $LOGREALM != 'l' ]
  then
    log=$(echo workdir/out/${LOGYEAR}_${LOGMEMBER}_${LOGREALM}.*.out.txt | tail -1)
    EXPNAME=$(echo $log|cut -d '.' -f1 | cut -d "/" -f3)
    if [[ $RUNNING =~ $EXPNAME ]]
    then
      echo $EXPNAME RUNNING $(echo $EXP | cut -d " " -f4)/$(echo $EXP | cut -d " " -f5) $(echo $EXP | cut -d " " -f6)
    else
      if [ -e $log ]
      then
        if ! grep "Tempo" $log > /dev/null
        then
          echo
          echo "***************************"
          echo $EXPNAME ERROR $(echo $EXP | cut -d " " -f4)/$(echo $EXP | cut -d " " -f5)
          NAME=$(basename $log | cut -d "." -f1)
          DIROUT=$(dirname $log)
          for output in $DIROUT/${NAME}*
          do
            if grep -i "Error" $output 
            then
              echo "==========================="
              echo $output
              OUTPUT_LOCATION=$(decode_cmip5_name $EXPNAME)
              echo $OUTPUT_LOCATION

              OPENING=$(grep Opening $output | tail -1)
              if [ "$OPENING" != "" ]
              then
                echo $OUTPUT_LOCATION/CGCM/$(echo $OPENING | cut -d " " -f2)
              fi
              
              echo $(grep Missing $output | tail -1)

              echo "==========================="
            fi
          done 
          echo "***************************"
          echo qsub workdir/set_cmip5_process-${EXPNAME}
          echo "***************************"
          echo
        else
          echo $EXPNAME OK
        fi
      else
        NUM=$(echo $EXP | cut -d " " -f4)
        DEN=$(echo $EXP | cut -d " " -f5)
        DONE=$(awk -vnum="$NUM" -vden="$DEN" 'BEGIN{print (num/den>=1)?1:0 }')
        if [ $DONE -eq 1 ]
        then
          echo $EXPNAME OK
        else
          echo $EXPNAME TODO $NUM/$DEN
        fi
      fi
    fi
  fi
done
